version:"3.9"

services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runaserver 0.0.0.0.8000"
    container_name: calculator_app
    volumes:
      - .:/calculator_app
    ports:
      - "8000:8000"