# Generated by Django 4.0.1 on 2022-01-12 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number1', models.IntegerField(default=0)),
                ('number2', models.IntegerField(default=0)),
                ('answer', models.IntegerField(null=True)),
            ],
        ),
    ]
